[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "9XKHUKki3mBjhkFrwvFqwdenTCykw8FH3YYdqT7f2Uru"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p nft-marketplace --test marketplace --test marketplace_failures"

[hooks]

[surfpool]
startup_wait = 5000
shutdown_wait = 2000
rpc_port = 8899
host = "127.0.0.1"
